### ISSUE TITLE
Remove margin on text?

### ISSUE THREAD

**Issue by JarrodMFlesch** [trbldesign/react-ui-components#1]
`TextWithInlineIcon`
I think we should let the user determine if they want to add margin instead of making them remove it. Thoughts?

**Comment by jacobsfletch** [comment]
@JarrodMFlesch That is because I am centering the icon vertically with the text, which is how we'd style 99% of these instances. BUT I do see what you mean, as a principle, we should absolutely style _as little possible_. I'm leaning toward agreeing that we should remove these style definitions, but like I said it would come at some cost as we apply these same styles over and over again.

**Comment by jacobsfletch** [comment]
@JarrodMFlesch What do you mean by "making them remove it"? Can you point to a line in the code as reference?

**Comment by jacobsfletch** [comment]
@JarrodMFlesch Any further description here?

**Comment by JarrodMFlesch** [comment]
I know I was referring to line 56 (https://github.com/trbldesign/custer/blob/develop/client/components/controls/Button/index.scss) when I opened this but I don't think it had anything to do with this, feel free to close 👍
